# Generated by Django 5.1.2 on 2024-10-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuarios_asignados',
            field=models.ManyToManyField(blank=True, related_name='tareas_asignadas', through='gestion_tareas.AsignacionTareas', to='gestion_tareas.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Progreso', 'Progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=10),
        ),
    ]
